{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "654ba733",
   "metadata": {},
   "outputs": [],
   "source": [
    "from agent import Agent\n",
    "from yinshEnv import YinshEnv\n",
    "from game import Game\n",
    "\n",
    "class Evaluation:\n",
    "    def __init__(self, model_1_path: str, model_2_path: str):\n",
    "        self.model_1_path = model_1_path\n",
    "        self.model_2_path = model_2_path\n",
    "\n",
    "    def evaluate(self, n: int):\n",
    "        \"\"\"\n",
    "        두 모델이 서로 번갈아가며 플레이하며 n회 평가 (각 모델이 흑/백 각각 수행)\n",
    "        \"\"\"\n",
    "        score = {\n",
    "            \"model_1\": 0,\n",
    "            \"model_2\": 0,\n",
    "            \"draws\": 0\n",
    "        }\n",
    "\n",
    "        agent_1 = Agent(local_predictions=True, model_path=self.model_1_path)\n",
    "        agent_2 = Agent(local_predictions=True, model_path=self.model_2_path)\n",
    "\n",
    "        for i in range(n):\n",
    "            print(f\"\\n{'='*10} Match {i+1}/{n} {'='*10}\")\n",
    "\n",
    "            # Agent1 (White), Agent2 (Black)\n",
    "            env = YinshEnv()\n",
    "            game = Game(env, agent_1, agent_2)\n",
    "            result = game.play_one_game(stochastic=False)\n",
    "            if result == 1:\n",
    "                score[\"model_1\"] += 1\n",
    "            elif result == -1:\n",
    "                score[\"model_2\"] += 1\n",
    "            else:\n",
    "                score[\"draws\"] += 1\n",
    "\n",
    "            # Agent2 (White), Agent1 (Black)\n",
    "            env = YinshEnv()\n",
    "            game = Game(env, agent_2, agent_1)\n",
    "            result = game.play_one_game(stochastic=False)\n",
    "            if result == 1:\n",
    "                score[\"model_2\"] += 1\n",
    "            elif result == -1:\n",
    "                score[\"model_1\"] += 1\n",
    "            else:\n",
    "                score[\"draws\"] += 1\n",
    "\n",
    "        total_games = n * 2\n",
    "        return (\n",
    "            f\"\\n📊 Evaluation Summary ({total_games} games):\\n\"\n",
    "            f\"Model 1 ({self.model_1_path}): {score['model_1']} wins\\n\"\n",
    "            f\"Model 2 ({self.model_2_path}): {score['model_2']} wins\\n\"\n",
    "            f\"Draws: {score['draws']}\\n\"\n",
    "        )\n",
    "\n",
    "if __name__ == \"__main__\":\n",
    "    import argparse\n",
    "\n",
    "    parser = argparse.ArgumentParser(description=\"Evaluate two Yinsh models\")\n",
    "    parser.add_argument(\"model_1\", type=str, help=\"Path to model 1\")\n",
    "    parser.add_argument(\"model_2\", type=str, help=\"Path to model 2\")\n",
    "    parser.add_argument(\"nr_games\", type=int, help=\"Number of matchups (x2: each model plays white/black)\")\n",
    "\n",
    "    args = parser.parse_args()\n",
    "\n",
    "    evaluator = Evaluation(args.model_1, args.model_2)\n",
    "    result_summary = evaluator.evaluate(args.nr_games)\n",
    "    print(result_summary)\n"
   ]
  }
 ],
 "metadata": {
  "language_info": {
   "name": "python"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
