{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": None,
   "id": "e629f204",
   "metadata": {},
   "outputs": [],
   "source": [
    "# game.py\n",
    "\n",
    "from yinshEnv import YinshEnv\n",
    "from neural_agent import Agent #mcts에서 사용된 agent\n",
    "import numpy as np\n",
    "import uuid\n",
    "import os\n",
    "import config\n",
    "import logging\n",
    "\n",
    "class Game:\n",
    "    def __init__(self, env: YinshEnv, white: Agent, black: Agent):\n",
    "        self.env = env\n",
    "        self.white = white\n",
    "        self.black = black\n",
    "        self.memory = []\n",
    "\n",
    "    def reset(self):\n",
    "        self.env.reset()\n",
    "\n",
    "    def play_one_game(self, stochastic: bool = True) -> int:\n",
    "        \"\"\"\n",
    "        에이전트 두 명이 번갈아가며 Yinsh 게임을 플레이.\n",
    "        학습을 위한 메모리 저장.\n",
    "        \"\"\"\n",
    "        self.reset()\n",
    "        self.memory.append([])\n",
    "\n",
    "        while not self.env.done:\n",
    "            current_player = self.white if self.env.current_player == 1 else self.black\n",
    "            action = current_player.select_action(self.env, stochastic=stochastic)\n",
    "            if action is None:\n",
    "                logging.warning(\"No valid action. Game ends.\")\n",
    "                break\n",
    "            self.save_to_memory(self.env.get_state_string(), current_player.mcts.root.edges)\n",
    "            self.env.step(action)\n",
    "\n",
    "        winner = self.env.get_winner()\n",
    "        for i in range(len(self.memory[-1])):\n",
    "            self.memory[-1][i] = (self.memory[-1][i][0], self.memory[-1][i][1], winner)\n",
    "\n",
    "        self.save_game(\"yinsh_game\")\n",
    "        return winner\n",
    "\n",
    "    def save_to_memory(self, state_string: str, edges: list) -> None:\n",
    "        \"\"\"\n",
    "        저장용 메모리에 상태와 탐색 확률 기록\n",
    "        \"\"\"\n",
    "        if not edges:\n",
    "            return\n",
    "        sum_visits = sum(e.N for e in edges)\n",
    "        search_probs = {str(e.action): e.N / sum_visits for e in edges}\n",
    "        self.memory[-1].append((state_string, search_probs, None))\n",
    "\n",
    "    def save_game(self, name: str = \"yinsh_game\") -> None:\n",
    "        \"\"\"\n",
    "        메모리(.npy)로 게임 저장\n",
    "        \"\"\"\n",
    "        game_id = f\"{name}-{str(uuid.uuid4())[:8]}\"\n",
    "        os.makedirs(config.MEMORY_DIR, exist_ok=True)\n",
    "        path = os.path.join(config.MEMORY_DIR, f\"{game_id}.npy\")\n",
    "        np.save(path, self.memory[-1])\n",
    "        logging.info(f\"🎮 Game saved to {path}\")\n"
   ]
  }
 ],
 "metadata": {
  "language_info": {
   "name": "python"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
