{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": None,
   "id": "d655b5ab",
   "metadata": {},
   "outputs": [],
   "source": [
    "import torch\n",
    "import torch.nn as nn\n",
    "import torch.nn.functional as F\n",
    "\n",
    "class ResidualBlock(nn.Module):\n",
    "    def __init__(self, channels):\n",
    "        super(ResidualBlock, self).__init__()\n",
    "        self.conv1 = nn.Conv2d(channels, channels, kernel_size=3, padding=1, bias=False)\n",
    "        self.bn1 = nn.BatchNorm2d(channels)\n",
    "        self.conv2 = nn.Conv2d(channels, channels, kernel_size=3, padding=1, bias=False)\n",
    "        self.bn2 = nn.BatchNorm2d(channels)\n",
    "\n",
    "    def forward(self, x):\n",
    "        residual = x\n",
    "        out = F.relu(self.bn1(self.conv1(x)))\n",
    "        out = self.bn2(self.conv2(out))\n",
    "        out += residual\n",
    "        return F.relu(out)\n",
    "\n",
    "class YinshNet(nn.Module):\n",
    "    def __init__(self, input_channels=11, board_size=11, num_res_blocks=5, num_filters=64, policy_output_dim=200):\n",
    "        super(YinshNet, self).__init__()\n",
    "        self.conv1 = nn.Conv2d(input_channels, num_filters, kernel_size=3, padding=1, bias=False)\n",
    "        self.bn1 = nn.BatchNorm2d(num_filters)\n",
    "\n",
    "        self.res_blocks = nn.Sequential(\n",
    "            *[ResidualBlock(num_filters) for _ in range(num_res_blocks)]\n",
    "        )\n",
    "\n",
    "        # Policy Head\n",
    "        self.policy_conv = nn.Conv2d(num_filters, 2, kernel_size=1, bias=False)\n",
    "        self.policy_bn = nn.BatchNorm2d(2)\n",
    "        self.policy_fc = nn.Linear(2 * board_size * board_size, policy_output_dim)\n",
    "\n",
    "        # Value Head\n",
    "        self.value_conv = nn.Conv2d(num_filters, 1, kernel_size=1, bias=False)\n",
    "        self.value_bn = nn.BatchNorm2d(1)\n",
    "        self.value_fc1 = nn.Linear(board_size * board_size, 256)\n",
    "        self.value_fc2 = nn.Linear(256, 1)\n",
    "\n",
    "    def forward(self, x):\n",
    "        x = F.relu(self.bn1(self.conv1(x)))\n",
    "        x = self.res_blocks(x)\n",
    "\n",
    "        # Policy head\n",
    "        p = F.relu(self.policy_bn(self.policy_conv(x)))\n",
    "        p = p.view(p.size(0), -1)\n",
    "        p = F.log_softmax(self.policy_fc(p), dim=1)\n",
    "\n",
    "        # Value head\n",
    "        v = F.relu(self.value_bn(self.value_conv(x)))\n",
    "        v = v.view(v.size(0), -1)\n",
    "        v = F.relu(self.value_fc1(v))\n",
    "        v = torch.tanh(self.value_fc2(v))\n",
    "\n",
    "        return p, v\n"
   ]
  }
 ],
 "metadata": {
  "language_info": {
   "name": "python"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
