{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "2cc74f31",
   "metadata": {},
   "outputs": [],
   "source": [
    "import torch\n",
    "import numpy as np\n",
    "from yinshEnv import YinshEnv\n",
    "from train import Trainer\n",
    "from model import YinshNet \n",
    "import matplotlib.pyplot as plt\n",
    "\n",
    "def test_state_to_input():\n",
    "    print(\" Testing state_to_input...\")\n",
    "    env = YinshEnv()\n",
    "    state_str = env.get_state_string()\n",
    "    input_array = YinshEnv.state_to_input(state_str)\n",
    "    assert input_array.shape == (1, 11, 11, 11), f\"Expected shape (1,11,11,11), got {input_array.shape}\"\n",
    "    print(\"✅ Passed: state_to_input shape correct\")\n",
    "\n",
    "def test_model_forward_pass():\n",
    "    print(\"\\n🧪 Testing model forward pass...\")\n",
    "    model = YourModel()  # 실제 정의한 네트워크 클래스 사용\n",
    "    model.eval()\n",
    "\n",
    "    env = YinshEnv()\n",
    "    state_str = env.get_state_string()\n",
    "    input_tensor = torch.tensor(YinshEnv.state_to_input(state_str), dtype=torch.float32).permute(0, 3, 1, 2)  # NHWC → NCHW\n",
    "    with torch.no_grad():\n",
    "        policy, value = model(input_tensor)\n",
    "\n",
    "    assert policy.shape[1] == 200, \"Policy output shape mismatch\"\n",
    "    assert value.shape[1] == 1, \"Value output shape mismatch\"\n",
    "    print(\"✅ Passed: model produces expected output shapes\")\n",
    "\n",
    "def test_training_one_batch():\n",
    "    print(\"\\nTesting training with 1 dummy batch...\")\n",
    "    model = YourModel()\n",
    "    trainer = Trainer(model)\n",
    "\n",
    "    # 간단한 더미 상태 생성\n",
    "    env = YinshEnv()\n",
    "    state_str = env.get_state_string()\n",
    "    state_input = YinshEnv.state_to_input(state_str)[0]  # (11,11,11)\n",
    "\n",
    "    action_index = np.random.randint(0, 200)\n",
    "    dummy_action = action_index\n",
    "    dummy_value = np.random.uniform(-1, 1)\n",
    "\n",
    "    # 학습\n",
    "    dummy_data = [(state_input, dummy_action, dummy_value) for _ in range(32)]\n",
    "    history = trainer.train(dummy_data)\n",
    "    trainer.plot_loss(history)\n",
    "    trainer.save_model()\n",
    "\n",
    "    print(\"✅ Passed: training works with dummy data\")\n",
    "\n",
    "def test_visual_output():\n",
    "    print(\"\\n Testing loss plot visualization...\")\n",
    "    x = list(range(50))\n",
    "    y1 = [np.sin(i / 5) + 0.5 for i in x]\n",
    "    y2 = [np.cos(i / 7) for i in x]\n",
    "    plt.plot(x, y1, label=\"dummy total_loss\")\n",
    "    plt.plot(x, y2, label=\"dummy value_loss\")\n",
    "    plt.legend()\n",
    "    plt.title(\"Dummy Loss Plot\")\n",
    "    plt.savefig(\"plots/dummy_loss_plot.png\")\n",
    "    print(\"✅ Dummy loss plot saved\")\n",
    "\n",
    "if __name__ == \"__main__\":\n",
    "    test_state_to_input()\n",
    "    test_model_forward_pass()\n",
    "    test_training_one_batch()\n",
    "    test_visual_output()\n"
   ]
  }
 ],
 "metadata": {
  "language_info": {
   "name": "python"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
