{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "fbe072e4",
   "metadata": {},
   "outputs": [],
   "source": [
    "import os\n",
    "import torch\n",
    "import torch.nn as nn\n",
    "import torch.optim as optim\n",
    "from torch.utils.data import Dataset, DataLoader\n",
    "import numpy as np\n",
    "import matplotlib.pyplot as plt\n",
    "from datetime import datetime\n",
    "import pandas as pd\n",
    "from tqdm import tqdm\n",
    "\n",
    "# ==== 설정 ====\n",
    "BATCH_SIZE = 32\n",
    "LEARNING_RATE = 0.001\n",
    "AMOUNT_OF_RESIDUAL_BLOCKS = 5\n",
    "CONVOLUTION_FILTERS = 64\n",
    "INPUT_SHAPE = (11, 11, 11)  # (C, H, W)\n",
    "POLICY_OUTPUT_SIZE = 200\n",
    "MODEL_FOLDER = \"models\"\n",
    "LOSS_PLOTS_FOLDER = \"plots\"\n",
    "\n",
    "# ==== 데이터셋 클래스 ====\n",
    "class YinshDataset(Dataset):\n",
    "    def __init__(self, data):\n",
    "        self.data = data\n",
    "\n",
    "    def __len__(self):\n",
    "        return len(self.data)\n",
    "\n",
    "    def __getitem__(self, idx):\n",
    "        state, action, value = self.data[idx]\n",
    "        state = torch.tensor(state, dtype=torch.float32)  # (C, H, W)\n",
    "        action_vec = torch.zeros(POLICY_OUTPUT_SIZE)\n",
    "        action_vec[hash(action) % POLICY_OUTPUT_SIZE] = 1.0\n",
    "        value = torch.tensor([value], dtype=torch.float32)\n",
    "        return state, action_vec, value\n",
    "\n",
    "# ==== 학습 클래스 ====\n",
    "class Trainer:\n",
    "    def __init__(self, model):\n",
    "        self.model = model\n",
    "        self.optimizer = optim.Adam(model.parameters(), lr=LEARNING_RATE)\n",
    "        self.policy_loss_fn = nn.KLDivLoss(reduction='batchmean')\n",
    "        self.value_loss_fn = nn.MSELoss()\n",
    "\n",
    "    def train(self, data):\n",
    "        dataset = YinshDataset(data)\n",
    "        dataloader = DataLoader(dataset, batch_size=BATCH_SIZE, shuffle=True)\n",
    "        self.model.train()\n",
    "\n",
    "        history = []\n",
    "        for epoch in tqdm(range(2 * max(5, len(dataset) // BATCH_SIZE)), desc=\"Training batches\"):\n",
    "            total_loss = 0\n",
    "            for states, policy_targets, value_targets in dataloader:\n",
    "                states = states.to(torch.device(\"cpu\"))\n",
    "                policy_targets = policy_targets.to(torch.device(\"cpu\"))\n",
    "                value_targets = value_targets.to(torch.device(\"cpu\"))\n",
    "\n",
    "                self.optimizer.zero_grad()\n",
    "                pred_policy, pred_value = self.model(states)\n",
    "                \n",
    "                loss_policy = self.policy_loss_fn(pred_policy, policy_targets)\n",
    "                loss_value = self.value_loss_fn(pred_value, value_targets)\n",
    "                loss = 0.5 * loss_policy + 0.5 * loss_value\n",
    "\n",
    "                loss.backward()\n",
    "                self.optimizer.step()\n",
    "                \n",
    "                history.append({\n",
    "                    \"total_loss\": loss.item(),\n",
    "                    \"policy_loss\": loss_policy.item(),\n",
    "                    \"value_loss\": loss_value.item()\n",
    "                })\n",
    "        return history\n",
    "\n",
    "    def plot_loss(self, history):\n",
    "        df = pd.DataFrame(history)\n",
    "        plt.plot(df['total_loss'], label='total_loss')\n",
    "        plt.plot(df['policy_loss'], label='policy_loss')\n",
    "        plt.plot(df['value_loss'], label='value_loss')\n",
    "        plt.legend()\n",
    "        plt.title(f\"Loss over time (lr={LEARNING_RATE})\")\n",
    "        os.makedirs(LOSS_PLOTS_FOLDER, exist_ok=True)\n",
    "        name = f\"loss-{datetime.now().strftime('%Y%m%d-%H%M%S')}.png\"\n",
    "        plt.savefig(os.path.join(LOSS_PLOTS_FOLDER, name))\n",
    "        print(\" Loss plot saved.\")\n",
    "\n",
    "    def save_model(self):\n",
    "        os.makedirs(MODEL_FOLDER, exist_ok=True)\n",
    "        path = os.path.join(MODEL_FOLDER, f\"model-{datetime.now().strftime('%Y%m%d-%H%M%S')}.pt\")\n",
    "        torch.save(self.model.state_dict(), path)\n",
    "        print(f\" Model saved to {path}\")"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
